# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171126_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('default', 'Default'), ('red', 'Red'), ('yellow', 'Yellow'), ('blue', 'Blue')], default='default', max_length=120),
        ),
    ]
