# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_note_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('default', 'Default'), ('blue', 'Blue'), ('red', 'Red'), ('yellow', 'Yellow')], default='default', max_length=120),
        ),
    ]
